-- Tüm VARCHAR ve TEXT limitleri LONGTEXT'e çevir
-- LONGTEXT: 4GB karakter kapasitesi (4,294,967,295 karakter)

USE ogubenn_portfolyo_db;

-- MySQL max_allowed_packet kontrolü (minimum 64MB olmalı)
SHOW VARIABLES LIKE 'max_allowed_packet';

-- Project tablosu
ALTER TABLE `Project` 
  MODIFY COLUMN `title` LONGTEXT NOT NULL,
  MODIFY COLUMN `category` VARCHAR(191) NOT NULL,
  MODIFY COLUMN `description` LONGTEXT NOT NULL,
  MODIFY COLUMN `shortDesc` LONGTEXT NOT NULL,
  MODIFY COLUMN `thumbnail` LONGTEXT NULL,
  MODIFY COLUMN `videoUrl` LONGTEXT NULL,
  MODIFY COLUMN `demoUrl` LONGTEXT NULL,
  MODIFY COLUMN `githubUrl` LONGTEXT NULL,
  MODIFY COLUMN `technologies` LONGTEXT NOT NULL,
  MODIFY COLUMN `tags` LONGTEXT NOT NULL,
  MODIFY COLUMN `duration` LONGTEXT NULL,
  MODIFY COLUMN `problem` LONGTEXT NULL,
  MODIFY COLUMN `solution` LONGTEXT NULL,
  MODIFY COLUMN `process` LONGTEXT NULL,
  MODIFY COLUMN `learnings` LONGTEXT NULL;

-- WorkExperience tablosu
ALTER TABLE `WorkExperience` 
  MODIFY COLUMN `company` LONGTEXT NOT NULL,
  MODIFY COLUMN `position` LONGTEXT NOT NULL,
  MODIFY COLUMN `description` LONGTEXT NOT NULL,
  MODIFY COLUMN `location` LONGTEXT NULL,
  MODIFY COLUMN `type` VARCHAR(191) NULL;

-- Service tablosu
ALTER TABLE `Service` 
  MODIFY COLUMN `title` LONGTEXT NOT NULL,
  MODIFY COLUMN `description` LONGTEXT NOT NULL,
  MODIFY COLUMN `icon` VARCHAR(191) NOT NULL,
  MODIFY COLUMN `features` LONGTEXT NOT NULL;

-- SiteSettings tablosu
ALTER TABLE `SiteSettings` 
  MODIFY COLUMN `heroTitle` LONGTEXT NOT NULL,
  MODIFY COLUMN `heroSubtitle` LONGTEXT NOT NULL,
  MODIFY COLUMN `heroBio` LONGTEXT NULL,
  MODIFY COLUMN `heroCTA` LONGTEXT NULL,
  MODIFY COLUMN `heroImage` LONGTEXT NULL,
  MODIFY COLUMN `aboutTitle` LONGTEXT NULL,
  MODIFY COLUMN `aboutDescription` LONGTEXT NOT NULL,
  MODIFY COLUMN `aboutBio1` LONGTEXT NULL,
  MODIFY COLUMN `aboutBio2` LONGTEXT NULL,
  MODIFY COLUMN `aboutBio3` LONGTEXT NULL,
  MODIFY COLUMN `aboutImage` LONGTEXT NULL,
  MODIFY COLUMN `workApproach` LONGTEXT NULL,
  MODIFY COLUMN `cvFileUrl` LONGTEXT NULL,
  MODIFY COLUMN `testFileUrl` LONGTEXT NULL,
  MODIFY COLUMN `contactEmail` LONGTEXT NULL,
  MODIFY COLUMN `contactPhone` LONGTEXT NULL,
  MODIFY COLUMN `contactLocation` LONGTEXT NULL,
  MODIFY COLUMN `socialLinks` LONGTEXT NOT NULL,
  MODIFY COLUMN `siteTitle` LONGTEXT NULL,
  MODIFY COLUMN `siteDescription` LONGTEXT NULL,
  MODIFY COLUMN `siteKeywords` LONGTEXT NULL,
  MODIFY COLUMN `ogImage` LONGTEXT NULL;

SELECT 'Migration completed - All VARCHAR/TEXT fields converted to LONGTEXT' AS status;
